<a href="https://colab.research.google.com/github/NatalhyBB/Examen-Final/blob/Evidencias/examen_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Examen Práctico: Fundamentos y Algoritmia para Inteligencia Artificial

In [45]:
# Parte 1:Fundamentos Numpy
import numpy as np

# 1. Arreglo del 1 al 20
arr = np.arange(1, 21)
print("1) Arreglo 1D (1 al 20):\n", arr, "\n")
print("═" * 60)

# 2. Selección de múltiplos de 3
multiplos_3 = arr[arr % 3 == 0]
print("2) Múltiplos de 3:\n", multiplos_3, "\n")
print("═" * 60)

# 3. Matriz aleatoria 5x5
np.random.seed(42)
matriz = np.random.rand(5, 5)
print("3) Matriz aleatoria 5x5:\n", matriz, "\n")
print("═" * 60)

# 4. Estadísticos básicos
media = np.mean(matriz)
desviacion = np.std(matriz)
maximo = np.max(matriz)

print("4) Estadísticos de la matriz:")
print(f"   → Media              : {media:.2f}")
print(f"   → Desviación estándar: {desviacion:.2f}")
print(f"   → Valor máximo       : {maximo:.2f}\n")
print("═" * 60)

# 5. Transformación a vector 1D
vector = matriz.flatten()
print("5) Vector 1D (matriz a plano):\n", vector, "\n")


1) Arreglo 1D (1 al 20):
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

════════════════════════════════════════════════════════════
2) Múltiplos de 3:
 [ 3  6  9 12 15 18] 

════════════════════════════════════════════════════════════
3) Matriz aleatoria 5x5:
 [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]] 

════════════════════════════════════════════════════════════
4) Estadísticos de la matriz:
   → Media              : 0.44
   → Desviación estándar: 0.28
   → Valor máximo       : 0.97

════════════════════════════════════════════════════════════
5) Vector 1D (matriz a plano):
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.2

In [46]:
# Parte 2: Fundamentos Pandas

import pandas as pd
from tabulate import tabulate

# Datos de estudiantes
data = {
    "Nombre": ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matemáticas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20]
}

df = pd.DataFrame(data)
col_alignment = ["center"] * len(df.columns)

print("1) Calificaciones de los estudiantes:")
print(tabulate(df, headers="keys", tablefmt="fancy_grid", showindex=False,  colalign=col_alignment))
print(" ")

# Promedio de cada columna numérica
promedios = df.mean(numeric_only=True).round(2)
promedios_df = promedios.reset_index()
promedios_df.columns = ["Columna", "Promedio"]

print("2) Promedio de cada columna numérica:")
print(tabulate( promedios_df, headers="keys", tablefmt="fancy_grid", showindex=False, colalign=["center", "center"]))
print(" ")

# Filtrar estudiantes con Nota_IA > 15
filtro_ia = df[df["Nota_IA"] > 15]
print("3) Estudiantes con Nota de IA mayor a 15")
print(tabulate( filtro_ia, headers="keys", tablefmt="fancy_grid", showindex=False, colalign=["center"] * len(filtro_ia.columns)))
print(" ")

# Agregar columna Promedio
df["Promedio"] = df[["Nota_Matemáticas", "Nota_IA"]].mean(axis=1).round(2)
print("4) DataFrame con columna 'Promedio'")
print(tabulate( df, headers="keys", tablefmt="fancy_grid", showindex=False, colalign=["center"] * len(df.columns)))
print(" ")

# Ordenar por 'Promedio' de mayor a menor
df_ordenado = df.sort_values(by="Promedio", ascending=False)
print("5) DataFrame ordenado por Promedio (descendente)")
print(tabulate( df_ordenado, headers="keys", tablefmt="fancy_grid", showindex=False, colalign=["center"] * len(df.columns)))
print(" ")


1) Calificaciones de los estudiantes:
╒══════════╤════════╤════════════════════╤═══════════╕
│  Nombre  │  Edad  │  Nota_Matemáticas  │  Nota_IA  │
╞══════════╪════════╪════════════════════╪═══════════╡
│   Ana    │   20   │         18         │    17     │
├──────────┼────────┼────────────────────┼───────────┤
│   Luis   │   21   │         15         │    14     │
├──────────┼────────┼────────────────────┼───────────┤
│  María   │   19   │         16         │    18     │
├──────────┼────────┼────────────────────┼───────────┤
│  Pedro   │   22   │         12         │    13     │
├──────────┼────────┼────────────────────┼───────────┤
│  Sofía   │   20   │         19         │    20     │
╘══════════╧════════╧════════════════════╧═══════════╛
 
2) Promedio de cada columna numérica:
╒══════════════════╤════════════╕
│     Columna      │  Promedio  │
╞══════════════════╪════════════╡
│       Edad       │    20.4    │
├──────────────────┼────────────┤
│ Nota_Matemáticas │     16     │
├──

In [47]:
# Parte 3: Algoritmia aplicada
# 1) Función que recibe lista de números
import numpy as np
import pandas as pd
from tabulate import tabulate

def analizar_lista(numeros):
    mayor = max(numeros)
    menor = min(numeros)
    promedio = sum(numeros) / len(numeros)
    return mayor, menor, promedio

entrada = input("Ingrese números separados por comas: ")
lista = [float(x) for x in entrada.split(",")]
mayor, menor, promedio = analizar_lista(lista)

print("\nResultados:")
print(f"➤ Mayor: {mayor}")
print(f"➤ Menor: {menor}")
print(f"➤ Promedio: {promedio:.2f}\n")

# 2) Función de activación Sigmoide con NumPy

def sigmoide(x):
    return 1 / (1 + np.exp(-x))
x = np.array([-2, -1, 0, 1, 2])
resultado = sigmoide(x)

print("2) Función Sigmoide aplicada a el arreglo: [-2, -1, 0, 1, 2]:")
print(resultado)
print("\n")

# 3) Clasificación de estudiantes

data = {
    "Nombre": ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matemáticas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20]
}
df = pd.DataFrame(data)


df["Promedio"] = df[["Nota_Matemáticas", "Nota_IA"]].mean(axis=1).round(2)

def clasificar(promedio):
    return "Aprobado" if promedio >= 14 else "Desaprobado"

df["Estado"] = df["Promedio"].apply(clasificar)

print("3) Clasificación de estudiantes:")
print(tabulate(
    df,
    headers="keys",
    tablefmt="fancy_grid",
    showindex=False,
    colalign=["center"] * len(df.columns)
))


Ingrese números separados por comas: 4, 67, 34, 78, 89, 12

Resultados:
➤ Mayor: 89.0
➤ Menor: 4.0
➤ Promedio: 47.33

2) Función Sigmoide aplicada a el arreglo: [-2, -1, 0, 1, 2]:
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


3) Clasificación de estudiantes:
╒══════════╤════════╤════════════════════╤═══════════╤════════════╤═════════════╕
│  Nombre  │  Edad  │  Nota_Matemáticas  │  Nota_IA  │  Promedio  │   Estado    │
╞══════════╪════════╪════════════════════╪═══════════╪════════════╪═════════════╡
│   Ana    │   20   │         18         │    17     │    17.5    │  Aprobado   │
├──────────┼────────┼────────────────────┼───────────┼────────────┼─────────────┤
│   Luis   │   21   │         15         │    14     │    14.5    │  Aprobado   │
├──────────┼────────┼────────────────────┼───────────┼────────────┼─────────────┤
│  María   │   19   │         16         │    18     │     17     │  Aprobado   │
├──────────┼────────┼────────────────────┼───────────┼────────────┼─────

In [48]:
# Parte 4: Mini-proyecto

import pandas as pd

datos = {
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Ventas_2024': [120, 340, 560, 230, 150],
    'Ventas_2025': [200, 400, 600, 300, 180]
}

df = pd.DataFrame(datos)

df.to_excel("ventas.xlsx", index=False)
print("Archivo 'ventas.xlsx' creado")
print("")
df = pd.read_excel("ventas.xlsx")

# 1) Agregar columna de Crecimiento

df["Crecimiento"] = ((df["Ventas_2025"] - df["Ventas_2024"]) / df["Ventas_2024"]) * 100
df["Crecimiento"] = df["Crecimiento"].round(2)

tabla = tabulate(df, headers="keys", tablefmt="fancy_grid", showindex=False, colalign=("center", "center", "center", "center"))
print("1) Agregar columna de Crecimiento ")
print(tabla)

# 2) Identificar producto con mayor crecimiento

mayor_crecimiento = df.loc[df["Crecimiento"].idxmax()]

print("")
print("2) Identificar producto con mayor crecimiento")
print(tabla)

print("\nProducto con mayor crecimiento:")
print(mayor_crecimiento["Producto"], "→", mayor_crecimiento["Crecimiento"], "%")



Archivo 'ventas.xlsx' creado

1) Agregar columna de Crecimiento 
╒════════════╤═══════════════╤═══════════════╤═══════════════╕
│  Producto  │  Ventas_2024  │  Ventas_2025  │  Crecimiento  │
╞════════════╪═══════════════╪═══════════════╪═══════════════╡
│     A      │      120      │      200      │     66.67     │
├────────────┼───────────────┼───────────────┼───────────────┤
│     B      │      340      │      400      │     17.65     │
├────────────┼───────────────┼───────────────┼───────────────┤
│     C      │      560      │      600      │     7.14      │
├────────────┼───────────────┼───────────────┼───────────────┤
│     D      │      230      │      300      │     30.43     │
├────────────┼───────────────┼───────────────┼───────────────┤
│     E      │      150      │      180      │      20       │
╘════════════╧═══════════════╧═══════════════╧═══════════════╛

2) Identificar producto con mayor crecimiento
╒════════════╤═══════════════╤═══════════════╤═══════════════╕
│  Pro

In [49]:
# Parte 5: Resolución de ecuaciones

import numpy as np
from sympy import symbols, Eq, solve

print("=== Resolución de Ecuaciones ===")
print("1. Ecuación de primer grado (ax + b = 0)")
print("2. Ecuación cuadrática (ax² + bx + c = 0)")
opcion = input("Elija una opción (1 o 2): ")

# Caso 1: Primer grado

if opcion == "1":
    a = float(input("Ingrese el valor de a: "))
    b = float(input("Ingrese el valor de b: "))

    if a == 0:
        print("No es una ecuación válida (a=0).")
    else:
        x = -b / a
        print(f"\nEcuación: {a}x + {b} = 0")
        print(f"Solución: x = {x}")

# Caso 2: Segundo grado

elif opcion == "2":
    a = float(input("Ingrese el valor de a: "))
    b = float(input("Ingrese el valor de b: "))
    c = float(input("Ingrese el valor de c: "))

    if a == 0:
        print("\nEsto no es cuadrática, es de primer grado.")
        if b == 0:
            print("No es una ecuación válida (a=0, b=0).")
        else:
            x = -c / b
            print(f"Ecuación de primer grado: {b}x + {c} = 0 → x = {x}")
    else:

        discriminante = b**2 - 4*a*c
        raiz = np.sqrt(discriminante + 0j)
        x1 = (-b + raiz) / (2*a)
        x2 = (-b - raiz) / (2*a)
        print(f"\nEcuación: {a}x² + {b}x + {c} = 0")
        print("Soluciones:")
        print("x1 =", x1)
        print("x2 =", x2)


else:
    print("Opción no válida. Debe elegir 1 o 2.")


=== Resolución de Ecuaciones ===
1. Ecuación de primer grado (ax + b = 0)
2. Ecuación cuadrática (ax² + bx + c = 0)
Elija una opción (1 o 2): 2
Ingrese el valor de a: 5
Ingrese el valor de b: 9
Ingrese el valor de c: 5

Ecuación: 5.0x² + 9.0x + 5.0 = 0
Soluciones:
x1 = (-0.9+0.43588989435406744j)
x2 = (-0.9-0.43588989435406744j)
